Fix typo `X11APPJAIL_SERVICE` -> `X11APPJAIL_PROFILE`

diff --git a/APPSCRIPT b/APPSCRIPT
--- a/APPSCRIPT
+++ b/APPSCRIPT
@@ -11,7 +11,7 @@ BASEDIR=`realpath -- "${BASEDIR}"` || exit $?
 . "${BASEDIR}/default.conf"
 
 if ! printf "%s" "${X11APPJAIL_PROFILE}" | grep -qEe '^[a-zA-Z0-9][a-zA-Z0-9_-]*$'; then
-    echo "${0##*/}: ${X11APPJAIL_SERVICE}: invalid profile name" >&2
+    echo "${0##*/}: ${X11APPJAIL_PROFILE}: invalid profile name" >&2
     exit 1
 fi
 
