Many changes
* Add `X11APPJAIL_DEBUG` environment variable.
* Limit characters in `X11APPJAIL_PROFILE`.
* Add `X11APPJAIL_SERVICE` environment variable.
* Add `X11APPJAIL_SERVICE_FROM` environment variable.
* Now .desktop are installed as `${X11APPJAIL_PROFILE}`-`${DESKTOPFILE}`
  to support installation of multiple profiles at the same time.
* devel/xdg-utils is installed from each Makejail in order for OpenURL
  to work correctly.
* Add `X11APPJAIL_DATA` environment variable and use it as the root
  directory of `X11APPJAIL_DATADIR`.
* Add `X11APPJAIL_APPSDIR` environment variable and use it as the root
  directory of `X11APPJAIL_APPDIR`.
* Add symlink to `Service/`.
* Add Services feature.
* Add OpenURL service.

diff --git a/APPSCRIPT b/APPSCRIPT
--- a/APPSCRIPT
+++ b/APPSCRIPT
@@ -1,10 +1,19 @@
 #!/bin/sh
 
+if [ -n "${X11APPJAIL_DEBUG}" ]; then
+    set -x
+fi
+
 BASEDIR=`dirname -- "$0"` || exit $?
 BASEDIR=`realpath -- "${BASEDIR}"` || exit $?
 
 . "${BASEDIR}/app.conf"
 . "${BASEDIR}/default.conf"
+
+if ! printf "%s" "${X11APPJAIL_PROFILE}" | grep -qEe '^[a-zA-Z0-9][a-zA-Z0-9_-]*$'; then
+    echo "${0##*/}: ${X11APPJAIL_SERVICE}: invalid profile name" >&2
+    exit 1
+fi
 
 cd -- "${APPSCRIPT_PWD:-${BASEDIR}}" || exit $?
 
@@ -20,6 +29,12 @@ if [ -n "${APPSCRIPT_SCRIPT}" ] && [ -n "${X11APPJAIL_UNINSTALL}" ]; then
     rm -rf "${X11APPJAIL_APPDIR}"
     rm -rf "${X11APPJAIL_SHAREDIR}"
     rm -rf "${X11APPJAIL_LOCKDIR}"
+
+    exit 0
+fi
+
+if [ -n "${X11APPJAIL_SERVICE}" ] && [ -n "${X11APPJAIL_SERVICE_FROM}" ]; then
+    "${BASEDIR}/Services/service.sh" || exit $?
 
     exit 0
 fi
