Use -- to pass arguments as-is

diff --git a/share/examples/x11appjail/Apps/feh/run b/share/examples/x11appjail/Apps/feh/run
--- a/share/examples/x11appjail/Apps/feh/run
+++ b/share/examples/x11appjail/Apps/feh/run
@@ -21,28 +21,34 @@ IS_LOCAL=true
 if [ $# -gt 0 ]; then
     FILE="${@: -1}"
 
-    case "${FILE}" in
-        file://*) FILE="${FILE#file://}" ;;
-        jail://*) FILE="${FILE#jail://}"; IS_LOCAL=false ;;
-        *://*) IS_LOCAL=false ;;
-    esac
+    if [ "${FILE}" != "--" ]; then
+        case "${FILE}" in
+            file://*) FILE="${FILE#file://}" ;;
+            jail://*) FILE="${FILE#jail://}"; IS_LOCAL=false ;;
+            *://*) IS_LOCAL=false ;;
+        esac
 
-    if ${IS_LOCAL}; then
-        if run_as [ ! -e "${FILE}" ]; then
-            err "${FILE}: file not found or no read permission."
-            exit 1
+        if ${IS_LOCAL}; then
+            if run_as [ ! -e "${FILE}" ]; then
+                err "${FILE}: file not found or no read permission."
+                exit 1
+            fi
+
+            if run_as [ ! -f "${FILE}" ]; then
+                err "${FILE}: not a regular file."
+                exit 1
+            fi
         fi
 
-        if run_as [ ! -f "${FILE}" ]; then
-            err "${FILE}: not a regular file."
-            exit 1
+        if ${IS_LOCAL}; then
+            set -- "${@:1:$#-1}" "-"
+        elif [ -n "${FILE}" ]; then
+            set -- "${@:1:$#-1}" "${FILE}"
+        else
+            set -- "${@:1:$#-1}"
         fi
-    fi
-
-    if ${IS_LOCAL}; then
-        set -- "${@:1:$#-1}" "-"
     else
-        set -- "${@:1:$#-1}" "${FILE}"
+        unset FILE
     fi
 fi
 
